domain: sgalland.github.io
url: https://sgalland.github.io
title: Programming Resources
description: A list of programming resources for a wide variety of topics that I work on.
theme: just-the-docs
# color_scheme: dark

aux_links:
  Github Repository: https://github.com/sgalland/sgalland.github.io

aux_links_new_tab: true

nav_enabled: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
